# Generated by Django 5.1 on 2024-08-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(default='xxx@xxx.com', max_length=254),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='payment_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='serial_no',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='session_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='roll',
            field=models.PositiveBigIntegerField(),
        ),
    ]
