# Generated by Django 5.1 on 2024-08-26 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_studentmodel_email_studentmodel_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
