# Generated by Django 5.1 on 2024-09-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
    ]
