# Generated by Django 5.1 on 2024-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='task',
            field=models.ManyToManyField(related_name='categories', to='task.task'),
        ),
    ]
