# Generated by Django 5.1 on 2024-08-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
        ('task', '0002_remove_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='task',
            field=models.ManyToManyField(to='task.task'),
        ),
    ]
