# Generated by Django 5.1 on 2024-09-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20240903_0259'),
    ]

    operations = [
    ]
