# Generated by Django 5.1 on 2024-08-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_rename_name_album_album_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='author',
            new_name='musician',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='date_time_field',
            new_name='release_date',
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, null=True),
        ),
    ]
